package com.sumith.lab_sep4;

import java.io.IOException;

class Test46 
{
	public static void main(String[] args) throws IOException 
	{
		//methodA();
	}

	public static void methodA() throws Exception
	{
		System.out.println("Completed..");
	}
}
